name: Build for Linux
on: [ push, pull_request ]
jobs:
  build_linux:
    name: Tests for Linux
    runs-on: ubuntu-latest
    container: ubuntu:16.04
    steps:
    - name: Install dependencies for Linux
      run: |
        apt-get -qq update
        apt-get install -y -qq libc6-dev perl wget zip bzip2 clang
        sed -i 's/mozilla\/DST_Root_CA_X3\.crt/\!mozilla\/DST_Root_CA_X3\.crt/' /etc/ca-certificates.conf
        update-ca-certificates
    - name: Checkout for Linux
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Fetch static-deps
      run: travis/download-linux-static-deps.sh
    - name: Run Tests
      run: scripts/test.sh
